apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 2m
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "24.x.x"
  valuesFrom:
    - kind: Secret
      name: mysql-secret
      valuesKey: values.yaml
