apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      version: "latest"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  values:
    mariadb:
      image:
        registry: docker.io
        repository: bitnami/mariadb
        tag: 11.4.10-debian-12-r0
  valuesFrom:
    - kind: Secret
      name: mysql-secret
      valuesKey: values.yaml
