apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: wordpress
      version: 24.2.11
      sourceRef:
        kind: OCIRepository
        name: bitnami
        namespace: flux-system
  values:
    mariadb:
      enabled: false
