apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  timeout: 15m
  releaseName: wordpress

  chart:
    spec:
      chart: wordpress
      version: "23.1.26"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  values:
    service:
      type: ClusterIP

    persistence:
      enabled: false   # 🔑 THIS FIXES THE PVC ERROR

    mariadb:
      image:
        registry: docker.io
        repository: bitnami/mariadb
        tag: 11.3.2-debian-11-r0

  valuesFrom:
    - kind: Secret
      name: mysql-secret
      valuesKey: values.yaml
