apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: default
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:gcBCpzRNyFUYaaa8RbksVeKjtawPnaVKPcY/9fU15wl620IL5bNrUUQc39FGo0Mwi0kxNIXzThhejJi16BNDxWqpCwb60QyE1VWpM42RCZjs3zWPMhxHkdtCZy5wzLgNq+iA/w88Y4G/b5M7TOSX3KJtxxzENbM7KQuO2P1hf0PQCRownsukTiplI1xM0q5VT1W9BVafQz1h4NbLHi0azX4=,iv:tO6z7l/YiSOcfoiGw4EqKsJ/JjiumOaM7HeG0smufEg=,tag:8/weqL5W8uSi+10KQKp09g==,type:str]
sops:
    age:
        - recipient: age16rxcx2k5h8klrvn3qy2d8lzg7y7cg8hff5qx9vx3m6my263ngpssx4dpqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWjhNS0tEd1U0R2RWNHdQ
            cHF1TUxsVXVjaktDZWxMaHhNSWxqQkpOam5nCjQxVUNiZXo2L1o5SDRCeWJDL3gw
            T1Nnd21jQjArdjJaM0ptbVA1NDlSL1UKLS0tIGU5akpJQ0FTRmp6cDlRc0I4Q1U5
            SWx1WDJMMGozRWNvUGtTRTFPa0kyTTQKngPPE58abWFj44SlpJAoP3HRlDBf/kXJ
            mV0zZqd4QdskxpN7dkhRniA93jl0XcgpETK4LmNg6oqZOxx9TZYClw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T04:47:31Z"
    mac: ENC[AES256_GCM,data:YvuCLn9xiFudhX8PnWvKfKGSrCKmEEF+C3qhOeTswUY/+TsOLYgj7xoCxHf8VoW0bZjFA9PJEZg1qUrT2XBFbYu407B5bujFxbUSNwUC/X3TsuqrYGlK4y5kwji7jeTM1zp2EgFTBmDONvhzpnoAoRiMmwEsy/um7l+rByMJlag=,iv:hxag33n2uS25lBPQJrlq6tX4oxZ5Qytgai/gl9cu/C4=,tag:B0fAsgF/Rdl/9B6mnemjkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
