apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: default
type: Opaque
data:
    values.yaml: ENC[AES256_GCM,data:ecHKHW9RIgrwfYHQYpZwtw97Y4r3PNJwFctO7s1XLVth07yKlzKcC357OMtn3FR9nJI3ImsWPUwh00J49c9C9TZrhwU7GpUMdJSJkpH0AYLdFDBCyuXUgDL6xtTl5bvUIhnJHkJWG5QMzhpFSdIjLUw6vsc3YZvobqings4+cO++Ra5c45PzDadkmEQY9yATOjY77KKi3NAyJ+3uDl2NZjK1dptHJeYErvQgwW/lAMpmPYycI6rlZNhq1YmbIAKHElAvNVIACas9AUd+CJMEvElk5kJ+o831,iv:I6SXyolKVtPdAUt1CC6uhDQYb99zGGv8VabZ3nYRa1A=,tag:C1DG2N0LrNuHbemwlF5sVQ==,type:str]
sops:
    age:
        - recipient: age16rxcx2k5h8klrvn3qy2d8lzg7y7cg8hff5qx9vx3m6my263ngpssx4dpqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYjN3SlF6Y3RDTlZWRWJ3
            TjcxQ0lwLzExTUsxRFFiczBZZlQ1M2Z1YTJNClZISXo4bnRVcHhJV0tOdnZGOUdN
            S1FSVWVHb1ZWRlQzZUhDMnlicThHMEUKLS0tIEtUYkN2bFRDQVV2dnE5dVUzYkpM
            aVA1TDEwdTVNcExzTUNtMEVFZ0ZadW8KeQd9PmMhz9n5WL0zs3nDA37eBBbd9kWU
            QWEBqRREESBXcGOt3Bs+ptNI9FglLadWmfxWx5OujghjgKwZWsghrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T04:58:39Z"
    mac: ENC[AES256_GCM,data:JyHyRShqdCJgrKEdEuONlhPj0n+p39v2eTQ5KpuT4ozPU1jjMUjmEL6/jEPL0sd6vbato54AlHMqYIJ7je8eXCDxLSSc4KSioNPRKpTShhkLzoIwB5sC5flWVTpLNxgvm1/Juah/He2oJCkg5f4SPfpXrPXF9Byn6QGW0I3/VCo=,iv:n9/6iGqpGRAzv1QOIpWjI41vGJLygm3hRfjMKzdWEB0=,tag:xRqhXmQYGb9Y2JtRLawuww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
